In [1]:
print("hello world")

hello world

In [2]:
print("wow2")

wow2

In [3]:
import numpy as np
arr=np.array([1,2,3])
arr2= np.array([4,5,6])
print(arr + arr2)

[5 7 9]

In [4]:
import pandas as pd 
pd.__version__

'3.0.5'

In [5]:
data={
    'id':[1,2,3,4,5,4],
    'name':["hari","ram","sita","alex","merry","elsa"],
    'age':[24,25,23,21,None,23],
    'rank':[3,2,5,4,1,6],
    'score':[80,90,65,79,97,63]
}
df= pd.DataFrame(data)
print(df)

   id   name   age  rank  score
0   1   hari  24.0     3     80
1   2    ram  25.0     2     90
2   3   sita  23.0     5     65
3   4   alex  21.0     4     79
4   5  merry   NaN     1     97
5   4   elsa  23.0     6     63

In [6]:
df.to_csv('students.csv', index= False)
students= pd.read_csv('students.csv')
print(students.head(2))

   id  name   age  rank  score
0   1  hari  24.0     3     80
1   2   ram  25.0     2     90

In [7]:
students[['id','rank']]

   id  rank
0   1     3
1   2     2
2   3     5
3   4     4
4   5     1
5   4     6

In [8]:
high_scorers= students[students['score']>80]
sorted_high_scorers= high_scorers.sort_values(by='rank', ascending=True)
print(sorted_high_scorers)

   id   name   age  rank  score
4   5  merry   NaN     1     97
1   2    ram  25.0     2     90

In [9]:
students.fillna(20)

   id   name   age  rank  score
0   1   hari  24.0     3     80
1   2    ram  25.0     2     90
2   3   sita  23.0     5     65
3   4   alex  21.0     4     79
4   5  merry  20.0     1     97
5   4   elsa  23.0     6     63

In [10]:
students.drop_duplicates(subset=['id'], keep='first')

   id   name   age  rank  score
0   1   hari  24.0     3     80
1   2    ram  25.0     2     90
2   3   sita  23.0     5     65
3   4   alex  21.0     4     79
4   5  merry   NaN     1     97